// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "api-reto-sw",
    "version": "1"
  },
  "paths": {
    "/save": {
      "post": {
        "summary": "saveUser",
        "description": "",
        "operationId": "saveUser.post.save",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-users": {
      "get": {
        "summary": "getUsers",
        "description": "",
        "operationId": "getUsers.get.get-users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};